jboss-dockerfiles/infinispan

server/Dockerfile, wildfly-modules/Dockerfile
ISPN 7.1.0 Final was released couple of days ago:
http://blog.infinispan.org/2015/01/infinispan-710-final-released.html
=> Bump to ISPN 7.1.0

server/Dockerfile, wildfly-modules/Dockerfile
ISPN 7.2.0 is out, see http://blog.infinispan.org/2015/05/infinispan-720final-is-out.html
=> Bump to ISPN 7.2.0

README.md
https://issues.jboss.org/browse/ISPN-6838
=> ISPN-6838 Added info about versioning

server/Dockerfile
https://issues.jboss.org/browse/ISPN-6890
=> [8.2.x] ISPN-6890 Changes for Openshift compatibility

server/Dockerfile
Please also add the ```8.2.4.Final``` tag to the ```8.2.x``` branch.
=> Update to Infinispan 8.2.4.Final

server/Dockerfile, server/is_healthy.sh, server/is_running.sh
https://issues.jboss.org/browse/ISPN-6679
This PR depends on https://github.com/infinispan/infinispan/pull/4499
=> ISPN-6679 Added scripts for Health Check API

server/docker-entrypoint.sh
https://issues.jboss.org/browse/ISPN-7581
Changelog:
* Added memory and CPU autoscaling
* Allowed different format for configuration file
* Added help message
Test procedure:
* Use docker run -m <momory_in_MB>M for testing memory settings
* Use docker run --cpu-quota=<numer_of_vCPUs>00000
=> ISPN-7581 Bootstrap file enhancements

.travis.yml, README.md
PR for https://github.com/jboss-dockerfiles/infinispan/issues/43
=> Support CI on travis

ci/ci_check.sh, server/.s2i/bin/assemble, server/Dockerfile, server/README.md, server/docker-entrypoint.sh
https://issues.jboss.org/browse/ISPN-6885
=> ISPN-6885 S2I Scripts

server/Dockerfile
https://issues.jboss.org/browse/ISPN-7599
Please do not integrate before https://github.com/infinispan/infinispan/pull/5267 gets in.
=> ISPN-7599 Added Jolokia ports

server/Dockerfile
Reverts jboss-dockerfiles/infinispan#56
=> Revert "ISPN-7599 Added Jolokia ports"

ci/ci_check.sh, server/docker-entrypoint.sh
fixes #61 plus some formatting changes
=> Added CI check for domain mode

ci/ci_check.sh, server/docker-entrypoint.sh
=> Correctly specify secret in the host controller

server/README.md, server/docker-entrypoint.sh, server/is_healthy.sh, server/is_running.sh
This PR is necessary to get Infinispan working on highly constrained environments like OpenShift Online
=> Fix memory limits for OpenShift Online

ci/ci_check.sh
=> Exit when domain mode tests fail

ci/ci_check.sh, server/Dockerfile
=> Change server download URL

server/docker-entrypoint.sh
=> Append custom JAVA_OPTS to the container JAVA_OPTS

server/Dockerfile
=> Update to 9.3.3.Final

server/Dockerfile
=> 9.4.1.Final

server/Dockerfile
=> 9.4.3.Final

server/Dockerfile
=> 9.4.6.Final

server/Dockerfile
=> 10.0.0.Alpha3
